### ISSUE TITLE
Problem with loading list.

### ISSUE THREAD

**Issue by mikhoul** [sanchosa/m3u8_editor#1]
I tried to load many list to https://m3u8.online/ but every time I receive this error message:
![image](https://user-images.githubusercontent.com/5678673/50806761-06e4e700-12c6-11e9-9a68-995a72c18a2f.png)

Here's a link to one of those list: https://www.dropbox.com/s/vi232ep0b9qa5eb/M3u8TestList.m3u

Regards :octocat:

**Comment by sanchosa** [comment]
Thank You. I will check it.

**Comment by sanchosa** [comment]
I have checked your file. It doesn't contain special identifier of the m3u files.
Documentation that i used is [here](http://ss-iptv.com/en/users/documents/m3u)

> Any M3U file starts with #EXTM3U text identifier in the first line.

But i will removed this rule from the list parser that any file content can be parsed as m3u list.

**Comment by sanchosa** [comment]
Fixed this issue in v1.0.2
